import numpy as np
def mult(x: np.ndarray) -> np.ndarray: ...

class FactorSE2:
    def __init__(self, x: float, y: float, theta: float) -> None: ...
    def dx(self) -> float: ...
    def dy(self) -> float: ...
    def dtheta(self) -> float: ...

class Problem:
    def __init__(self) -> None: ...