from typing import List, Tuple
import numpy as np
def mult(x: np.ndarray) -> np.ndarray: ...

class FactorSE2:
    def __init__(self, x: float, y: float, theta: float) -> None: ...
    def dx(self) -> float: ...
    def dy(self) -> float: ...
    def dtheta(self) -> float: ...

class Problem:
    def __init__(self) -> None: ...
    def add_residual_block(self, dim_residual: int, variable_key_size_list: List[Tuple[str, int]]) -> None: ...

class Factor:
    def __init__(self, a: ...) -> None: ...