from typing import List, Tuple, Dict
import numpy as np


class Problem:
    def __init__(self) -> None: ...
    def add_residual_block(self, dim_residual: int, variable_key_size_list: List[Tuple[str, int]], factor) -> None: ...

class GaussNewtonOptimizer:
    def __init__(self) -> None: ...
    def optimize(self, problem: Problem, init_values: Dict[str, np.ndarray]) -> None: ...